package com.example.the_ultimate_easter_egg_guide.ToolsData;

import com.example.the_ultimate_easter_egg_guide.MapData.Maps;
import com.example.the_ultimate_easter_egg_guide.Models.Tools.RecommendedGobbleGums.GobbleGumSet;
import com.example.the_ultimate_easter_egg_guide.Models.Tools.RecommendedGobbleGums.GobbleGumSetTypes;

import java.util.Arrays;
import java.util.List;

public enum PlayerGumSets
{
    TEST_SET_1_PLAYER("Test Set - 1 Player", Maps.Test_TestingMap1, GobbleGumSetTypes.Test, 1, new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST)),
    TEST_SET_2_PLAYER("Test Set - 2 Players", Maps.Test_TestingMap1, GobbleGumSetTypes.Test, 2, new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST), new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST)),
    TEST_SET_3_PLAYER("Test Set - 3 Players", Maps.Test_TestingMap1, GobbleGumSetTypes.Test, 3, new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST), new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST), new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST)),
    TEST_SET_4_PLAYER("Test Set - 4 Players", Maps.Test_TestingMap1, GobbleGumSetTypes.Test, 4, new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST), new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST), new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST), new GobbleGumSet(GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST, GobbleGums.TEST)),

    // SOLO EASTER EGG SETS

    THE_GIANT_CLASSIC("The Giant - Solo", Maps.BOIII_The_Giant, GobbleGumSetTypes.CLASSIC_ONLY, 1, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE)),
    THE_GIANT_MEGA("The Giant - Solo", Maps.BOIII_The_Giant, GobbleGumSetTypes.MEGA, 1, new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.SHOPPING_FREE, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.CRATE_POWER, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    THE_GIANT_WHIMSICAL("The Giant - Solo", Maps.BOIII_The_Giant, GobbleGumSetTypes.WHIMSICAL, 1, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    DER_EISENDRACHE_CLASSIC("Der Eisendrache - Solo", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.CLASSIC_ONLY, 1, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION)),
    DER_EISENDRACHE_MEGA("Der Eisendrache - Solo", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.MEGA, 1, new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.SHOPPING_FREE, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IDLE_EYES, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    DER_EISENDRACHE_WHIMSICAL("Der Eisendrache - Solo", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.WHIMSICAL, 1, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    ZETSUBOU_NO_SHIMA_CLASSIC("Zetsubou No Shima - Solo", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.CLASSIC_ONLY, 1, new GobbleGumSet(GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION)),
    ZETSUBOU_NO_SHIMA_MEGA("Zetsubou No Shima - Solo", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.MEGA, 1, new GobbleGumSet(GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.PERKAHOLIC, GobbleGums.SHOPPING_FREE, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    ZETSUBOU_NO_SHIMA_WHIMSICAL("Zetsubou No Shima - Solo", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.WHIMSICAL, 1, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    GOROD_KROVI_CLASSIC("Gorod Krovi - Solo", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.CLASSIC_ONLY, 1, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION)),
    GOROD_KROVI_MEGA("Gorod Krovi - Solo", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.MEGA, 1, new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.SHOPPING_FREE, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IDLE_EYES, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    GOROD_KROVI_WHIMSICAL("Gorod Krovi - Solo", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.WHIMSICAL, 1, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    REVELATIONS_CLASSIC("Revelations - Solo", Maps.BOIII_Revelations, GobbleGumSetTypes.CLASSIC_ONLY, 1, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION)),
    REVELATIONS_MEGA("Revelations - Solo", Maps.BOIII_Revelations, GobbleGumSetTypes.MEGA, 1, new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.SHOPPING_FREE, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IDLE_EYES, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    REVELATIONS_WHIMSICAL("Revelations - Solo", Maps.BOIII_Revelations, GobbleGumSetTypes.WHIMSICAL, 1, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    //DUO Easter Egg Sets
    THE_GIANT_CLASSIC_2_PLAYER("The Giant - 2 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.CLASSIC_ONLY, 2, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.ANYWHERE_BUT_HERE)),
    THE_GIANT_MEGA_2_PLAYER("The Giant - 2 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.MEGA, 2, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.CRATE_POWER, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.CRATE_POWER, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT)),
    THE_GIANT_WHIMSICAL_2_PLAYER("The Giant - 2 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.WHIMSICAL, 2, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    DER_EISENDRACHE_CLASSIC_2_PLAYER("Der Eisendrache - 2 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.CLASSIC_ONLY, 2, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT)),
    DER_EISENDRACHE_MEGA_2_PLAYER("Der Eisendrache - 2 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.MEGA, 2, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IDLE_EYES, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT)),
    DER_EISENDRACHE_WHIMSICAL_2_PLAYER("Der Eisendrache - 2 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.WHIMSICAL, 2, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    ZETSUBOU_NO_SHIMA_CLASSIC_2_PLAYER("Zetsubou No Shima - 2 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.CLASSIC_ONLY, 2, new GobbleGumSet(GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT)),
    ZETSUBOU_NO_SHIMA_MEGA_2_PLAYER("Zetsubou No Shima - 2 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.MEGA, 2, new GobbleGumSet(GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    ZETSUBOU_NO_SHIMA_WHIMSICAL_2_PLAYER("Zetsubou No Shima - 2 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.WHIMSICAL, 2, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    GOROD_KROVI_CLASSIC_2_PLAYER("Gorod Krovi - 2 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.CLASSIC_ONLY, 2, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT)),
    GOROD_KROVI_MEGA_2_PLAYER("Gorod Krovi - 2 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.MEGA, 2, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.IDLE_EYES, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IN_PLAIN_SIGHT)),
    GOROD_KROVI_WHIMSICAL_2_PLAYER("Gorod Krovi - 2 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.WHIMSICAL, 2, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    REVELATIONS_CLASSIC_2_PLAYER("Revelations - 2 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.CLASSIC_ONLY, 2, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE)),
    REVELATIONS_MEGA_2_PLAYER("Revelations - 2 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.MEGA, 2, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT)),
    REVELATIONS_WHIMSICAL_2_PLAYER("Revelations - 2 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.WHIMSICAL, 2, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE)),

    // TRIO Easter Egg Sets
    THE_GIANT_CLASSIC_3_PLAYER("The Giant - 3 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.CLASSIC_ONLY, 3, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.ANYWHERE_BUT_HERE), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.LUCKY_CRIT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE)),
    THE_GIANT_MEGA_3_PLAYER("The Giant - 3 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.MEGA, 3, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.CRATE_POWER, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.CRATE_POWER, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.PHOENIX_UP, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    THE_GIANT_WHIMSICAL_3_PLAYER("The Giant - 3 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.WHIMSICAL, 3, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.EYE_CANDY, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.NEWTONIAN_NEGATION)),

    DER_EISENDRACHE_CLASSIC_3_PLAYER("Der Eisendrache - 3 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.CLASSIC_ONLY, 3, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.LUCKY_CRIT, GobbleGums.STOCK_OPTION)),
    DER_EISENDRACHE_MEGA_3_PLAYER("Der Eisendrache - 3 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.MEGA, 3, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IDLE_EYES, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.PHOENIX_UP, GobbleGums.REIGN_DROPS, GobbleGums.IDLE_EYES, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    DER_EISENDRACHE_WHIMSICAL_3_PLAYER("Der Eisendrache - 3 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.WHIMSICAL, 3, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT)),

    ZETSUBOU_NO_SHIMA_CLASSIC_3_PLAYER("Zetsubou No Shima - 3 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.CLASSIC_ONLY, 3, new GobbleGumSet(GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT)),
    ZETSUBOU_NO_SHIMA_MEGA_3_PLAYER("Zetsubou No Shima - 3 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.MEGA, 3, new GobbleGumSet(GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.PHOENIX_UP, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    ZETSUBOU_NO_SHIMA_WHIMSICAL_3_PLAYER("Zetsubou No Shima - 3 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.WHIMSICAL, 3, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT)),

    GOROD_KROVI_CLASSIC_3_PLAYER("Gorod Krovi - 3 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.CLASSIC_ONLY, 3, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT)),
    GOROD_KROVI_MEGA_3_PLAYER("Gorod Krovi - 3 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.MEGA, 3, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.IDLE_EYES, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.PHOENIX_UP, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    GOROD_KROVI_WHIMSICAL_3_PLAYER("Gorod Krovi - 3 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.WHIMSICAL, 3, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT)),

    REVELATIONS_CLASSIC_3_PLAYER("Revelations - 3 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.CLASSIC_ONLY, 3, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.LUCKY_CRIT, GobbleGums.STOCK_OPTION)),
    REVELATIONS_MEGA_3_PLAYER("Revelations - 3 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.MEGA, 3, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.PHOENIX_UP, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    REVELATIONS_WHIMSICAL_3_PLAYER("Revelations - 3 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.WHIMSICAL, 3, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT)),

    // Quad Easter Egg Sets
    SHADOWS_OF_EVIL_CLASSIC_4_PLAYER("Shadows of Evil - 4 Player", Maps.BOIII_Shadows_Of_Evil, GobbleGumSetTypes.CLASSIC_ONLY, 4, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.NOW_YOU_SEE_ME, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.NOW_YOU_SEE_ME, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.LUCKY_CRIT)),
    SHADOWS_OF_EVIL_MEGA_4_PLAYER("Shadows of Evil - 4 Player", Maps.BOIII_Shadows_Of_Evil, GobbleGumSetTypes.MEGA, 4, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.FEAR_IN_HEADLIGHTS, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.FEAR_IN_HEADLIGHTS, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.FEAR_IN_HEADLIGHTS, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.PHOENIX_UP), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.FEAR_IN_HEADLIGHTS, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT)),
    SHADOWS_OF_EVIL_WHIMSICAL_4_PLAYER("Shadows of Evil - 4 Player", Maps.BOIII_Shadows_Of_Evil, GobbleGumSetTypes.WHIMSICAL, 4, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT), new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.PROJECTILE_VOMITING, GobbleGums.EYE_CANDY, GobbleGums.SLAUGHTER_SLIDE, GobbleGums.DISORDERLY_COMBAT)),

    THE_GIANT_CLASSIC_4_PLAYER("The Giant - 4 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.CLASSIC_ONLY, 4, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.ANYWHERE_BUT_HERE), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.LUCKY_CRIT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.LUCKY_CRIT, GobbleGums.STOCK_OPTION)),
    THE_GIANT_MEGA_4_PLAYER("The Giant - 4 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.MEGA, 4, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.CRATE_POWER, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.CRATE_POWER, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.PHOENIX_UP, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.WALL_POWER, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT)),
    THE_GIANT_WHIMSICAL_4_PLAYER("The Giant - 4 Player", Maps.BOIII_The_Giant, GobbleGumSetTypes.WHIMSICAL, 4, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.EYE_CANDY, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.NEWTONIAN_NEGATION), new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.TONE_DEATH, GobbleGums.SLAUGHTER_SLIDE)),

    DER_EISENDRACHE_CLASSIC_4_PLAYER("Der Eisendrache - 4 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.CLASSIC_ONLY, 4, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.LUCKY_CRIT, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE)),
    DER_EISENDRACHE_MEGA_4_PLAYER("Der Eisendrache - 4 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.MEGA, 4, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IDLE_EYES, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.PHOENIX_UP, GobbleGums.REIGN_DROPS, GobbleGums.IDLE_EYES, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IN_PLAIN_SIGHT)),
    DER_EISENDRACHE_WHIMSICAL_4_PLAYER("Der Eisendrache - 4 Player", Maps.BOIII_Der_Eisendrache, GobbleGumSetTypes.WHIMSICAL, 4, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT), new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.PROJECTILE_VOMITING, GobbleGums.EYE_CANDY, GobbleGums.SLAUGHTER_SLIDE, GobbleGums.DISORDERLY_COMBAT)),

    ZETSUBOU_NO_SHIMA_CLASSIC_4_PLAYER("Zetsubou No Shima - 4 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.CLASSIC_ONLY, 4, new GobbleGumSet(GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.LUCKY_CRIT, GobbleGums.STOCK_OPTION)),
    ZETSUBOU_NO_SHIMA_MEGA_4_PLAYER("Zetsubou No Shima - 4 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.MEGA, 4, new GobbleGumSet(GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.PHOENIX_UP, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ALCHEMICAL_ANTITHESIS)),
    ZETSUBOU_NO_SHIMA_WHIMSICAL_4_PLAYER("Zetsubou No Shima - 4 Player", Maps.BOIII_Zetsubou_No_Shima, GobbleGumSetTypes.WHIMSICAL, 4, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.PROJECTILE_VOMITING, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT), new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.SLAUGHTER_SLIDE)),

    GOROD_KROVI_CLASSIC_4_PLAYER("Gorod Krovi - 4 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.CLASSIC_ONLY, 4, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE)),
    GOROD_KROVI_MEGA_4_PLAYER("Gorod Krovi - 4 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.MEGA, 4, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.IDLE_EYES, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.PHOENIX_UP, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.UNDEAD_MAN_WALKING, GobbleGums.IDLE_EYES, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT)),
    GOROD_KROVI_WHIMSICAL_4_PLAYER("Gorod Krovi - 4 Player", Maps.BOIII_Gorod_Krovi, GobbleGumSetTypes.WHIMSICAL, 4, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT), new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.PROJECTILE_VOMITING, GobbleGums.EYE_CANDY, GobbleGums.SLAUGHTER_SLIDE, GobbleGums.DISORDERLY_COMBAT)),

    REVELATIONS_CLASSIC_4_PLAYER("Revelations - 4 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.CLASSIC_ONLY, 4, new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.STOCK_OPTION, GobbleGums.LUCKY_CRIT, GobbleGums.ANYWHERE_BUT_HERE), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ARSENAL_ACCELERATOR, GobbleGums.LUCKY_CRIT, GobbleGums.STOCK_OPTION), new GobbleGumSet(GobbleGums.ALCHEMICAL_ANTITHESIS, GobbleGums.IN_PLAIN_SIGHT, GobbleGums.ANYWHERE_BUT_HERE, GobbleGums.LUCKY_CRIT, GobbleGums.ARSENAL_ACCELERATOR)),
    REVELATIONS_MEGA_4_PLAYER("Revelations - 4 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.MEGA, 4, new GobbleGumSet(GobbleGums.SHOPPING_FREE, GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.NEAR_DEATH_EXPERIENCE, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.PHOENIX_UP, GobbleGums.REIGN_DROPS, GobbleGums.ALCHEMICAL_ANTITHESIS), new GobbleGumSet(GobbleGums.PERKAHOLIC, GobbleGums.IMMOLATION_LIQUIDATION, GobbleGums.IDLE_EYES, GobbleGums.REIGN_DROPS, GobbleGums.IN_PLAIN_SIGHT)),
    REVELATIONS_WHIMSICAL_4_PLAYER("Revelations - 4 Player", Maps.BOIII_Revelations, GobbleGumSetTypes.WHIMSICAL, 4, new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.EYE_CANDY, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.PROJECTILE_VOMITING, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.TONE_DEATH, GobbleGums.DISORDERLY_COMBAT, GobbleGums.SLAUGHTER_SLIDE), new GobbleGumSet(GobbleGums.EYE_CANDY, GobbleGums.PROJECTILE_VOMITING, GobbleGums.TONE_DEATH, GobbleGums.NEWTONIAN_NEGATION, GobbleGums.DISORDERLY_COMBAT), new GobbleGumSet(GobbleGums.NEWTONIAN_NEGATION, GobbleGums.PROJECTILE_VOMITING, GobbleGums.EYE_CANDY, GobbleGums.SLAUGHTER_SLIDE, GobbleGums.DISORDERLY_COMBAT)),

    ;

    public final String setName;
    public final Maps map;
    public final GobbleGumSetTypes setType;
    public final int playerCount;
    public final List<GobbleGumSet> gumSets;

    PlayerGumSets(String setName, Maps map, GobbleGumSetTypes setType, int playerCount, GobbleGumSet... gums)
    {
        this.setName = setName;
        this.map = map;
        this.setType = setType;
        this.playerCount = playerCount;
        this.gumSets = Arrays.asList(gums);
    }

}
