package com.example.the_ultimate_easter_egg_guide.MapData.BOII.Buildables;

import com.example.the_ultimate_easter_egg_guide.Models.Maps.Buildable;
import com.example.the_ultimate_easter_egg_guide.Models.Maps.BuildableStep;
import com.example.the_ultimate_easter_egg_guide.R;

import java.util.Arrays;
import java.util.List;

public class MOTD_Buildables
{
    public static final Buildable FreeBlundergat = new Buildable("Free Blundergat")
            .addStep(new BuildableStep("Prerequisite")
                    .addSubStep(new BuildableStep("Obtain the Hell's Retriever first. Reference the Hell's Retriever guide before starting this Easter egg."))
                    .addSubStep(new BuildableStep("The Blundergat from the Mystery Box does not count for the main quest or this guide.")))
            .addStep(new BuildableStep("Collect the Hidden Blue Skulls")
                    .addSubStep(new BuildableStep("Use the Hell's Retriever to collect five hidden blue skulls around the map."))
                    .addSubStep(new BuildableStep("Hold the tactical button to charge the Hell's Retriever before throwing it at each skull."))
                    .addSubStep(new BuildableStep("The skulls are only visible in Afterlife or through the Spectral Shield's spectral vision."))
                    .addSubStep(new BuildableStep("The skull locations are the same every game."))
                    .addSubStep(new BuildableStep("When the charged Hell's Retriever hits a skull, it will return to you with the skull attached.")))
            .addStep(new BuildableStep("Skull 1")
                    .addSubStep(new BuildableStep("In the cell block just outside the library in the spawn area."))
                    .addSubStep(new BuildableStep("The skull is inside a cell with a toilet. Glitch spot to collect first skull above the Hell's Retriever spawn."))
                    .addImage(R.drawable.boii_motd_skull1_main)
                    .addImage()
            )
            .addStep(new BuildableStep("Skull 2")
                    .addSubStep(new BuildableStep("On the roof, back left when coming onto the roof."))
                    .addSubStep(new BuildableStep("The skull is sitting on an unreachable corner of the roof.")))
            .addStep(new BuildableStep("Skull 3")
                    .addSubStep(new BuildableStep("On the docks, across the water on another dock."))
                    .addSubStep(new BuildableStep("Look near the third pillar from the left, close to the possible Mystery Box spawn."))
                    .addImage(R.drawable.boii_motd_skull3)
            )
            .addStep(new BuildableStep("Skull 4")
                    .addSubStep(new BuildableStep("Above Juggernog near the docks."))
                    .addSubStep(new BuildableStep("Look up at the lamppost on the hill."))
                    .addSubStep(new BuildableStep("You have to jump when throwing the Hell's Retriever, or collect it from the gondola as it moves.")))
            .addStep(new BuildableStep("Skull 5")
                    .addSubStep(new BuildableStep("In the Warden's Office, outside the window on a telephone pole."))
                    .addSubStep(new BuildableStep("Look out the window to line up the throw."))
                    .addSubStep(new BuildableStep("Do not board up the window because the planks can block the throw.")))
            .addStep(new BuildableStep("Claim the Free Blundergat")
                    .addSubStep(new BuildableStep("After all five skulls are collected, the Demonic Announcer will laugh."))
                    .addSubStep(new BuildableStep("The Blundergat will appear on the Warden's table in the Warden's Office."))
                    .addSubStep(new BuildableStep("Pick up the free Blundergat from the Warden's table."))
            );
    public static final Buildable HellsRetriever = new Buildable("Hell's Retriever")
            .addStep(new BuildableStep("Feed the dog Heads")
                    .addSubStep(new BuildableStep("Feed six zombies to each of the three dog heads around the map."))
                    .addSubStep(new BuildableStep("Each head must be fed six zombies. When a head is complete, it will recede into the wall and the Dog icon on the wall will glow.")))
            .addStep(new BuildableStep("Dog Head 1")
                    .addSubStep(new BuildableStep("In the Broadway cell block, located near the B23R."))
                    .addImage(R.drawable.boii_motd_dog1)
            )
            .addStep(new BuildableStep("Dog Head 2")
                    .addSubStep(new BuildableStep("In the infirmary, adjacent to the Afterlife power box.")))
            .addStep(new BuildableStep("Dog Head 3")
                    .addSubStep(new BuildableStep("Near the workbench on the lower level of the docks.")))
            .addStep(new BuildableStep("Claim the Hell's Retriever")
                    .addSubStep(new BuildableStep("Once all three heads have receded and the Dog head icons are glowing, an area opens in the Citadel Tunnels beneath the sign of the three dog heads."))
                    .addSubStep(new BuildableStep("Go down there and pick up the Hell's Retriever."))
            );
    public static final Buildable HellsRedeemer = new Buildable("Hell's Redeemer")
            .addStep(new BuildableStep("Prerequisite")
                    .addSubStep(new BuildableStep("Obtain the Hell's Retriever first. Reference the Hell's Retriever guide before starting this Easter egg.")))
            .addStep(new BuildableStep("Kill Zombies with the Hell's Retriever")
                    .addSubStep(new BuildableStep("Kill approximately 10-15 zombies with the Hell's Retriever."))
                    .addSubStep(new BuildableStep("When done correctly, you will hear the sound of entering Afterlife and some music.")))
            .addStep(new BuildableStep("Complete a Bridge Round")
                    .addSubStep(new BuildableStep("Go to the Golden Gate Bridge on round 10 or higher."))
                    .addSubStep(new BuildableStep("Spend at least one full round on the bridge using only the Hell's Retriever."))
                    .addSubStep(new BuildableStep("Kill at least 30 zombies with the Hell's Retriever during that round."))
                    .addSubStep(new BuildableStep("When the round ends, you should hear the Afterlife sound."))
                    .addSubStep(new BuildableStep("Do not shoot any weapons during this round or the step will reset. Knifing the air is allowed.")))
            .addStep(new BuildableStep("Throw the Hell's Retriever into Lava")
                    .addSubStep(new BuildableStep("Throw the Hell's Retriever into the lava pit underneath the Cerberus head near the B23R."))
                    .addSubStep(new BuildableStep("If done correctly, the Hell's Retriever will not return and you will hear the Afterlife sound again."))
                    .addSubStep(new BuildableStep("The lava is under the ramp that leads to the B23R and Cerberus head. Throw the retriever into the lava from there.")))
            .addStep(new BuildableStep("Pick Up the Hell's Redeemer")
                    .addSubStep(new BuildableStep("On any following round, go to the Citadel Tunnels where you originally obtained the Hell's Retriever."))
                    .addSubStep(new BuildableStep("The retriever should be gone and the aura should be blue instead of red."))
                    .addSubStep(new BuildableStep("Enter Afterlife and pick up the Hell's Redeemer."))
            );
    public static final Buildable AcidGatKit = new Buildable("Acid Gat Kit")
            .addStep(new BuildableStep("Choose a Crafting Table")
                    .addSubStep(new BuildableStep("Docks"))
                    .addSubStep(new BuildableStep("Cafeteria"))
                    .addSubStep(new BuildableStep("Behind Electric Cherry on the way up to the roof.")))
            .addStep(new BuildableStep("Find the Motor")
                    .addSubStep(new BuildableStep("Right as you enter the Warden's quarters, to the right of the wall buy on the floor."))
                    .addSubStep(new BuildableStep("To the left of the Mystery Box spawn on the floor in the Warden's Office."))
                    .addSubStep(new BuildableStep("To the left of the fireplace, to the left of Speed Cola in the Warden's Office.")))
            .addStep(new BuildableStep("Find the Case")
                    .addSubStep(new BuildableStep("Near the library through the C-D gate, sitting on a table near the jail cell.")
                            .addImage(R.drawable.boii_motd_acidgat_case1)
                    )
                    .addSubStep(new BuildableStep("Under the staircase in the hallway leading to the Warden's Office, also known as Michigan Avenue."))
                    .addSubStep(new BuildableStep("Near the top of the stairs from the laundromat, across from the Afterlife switch, on the floor.")))
            .addStep(new BuildableStep("Find the Acid Bottle")
                    .addSubStep(new BuildableStep("On the way up to the roof, in the left corridor opposite the bloody bathtubs, on a table."))
                    .addSubStep(new BuildableStep("In the second room with the bloody bathtubs on the way up to the roof."))
                    .addSubStep(new BuildableStep("In the first room with the bloody bathtubs."))
            );
    public static final Buildable ZombieShield = new Buildable("Zombie Shield", "A back-mounted shield that protects from rear attacks and can be used as a melee weapon.")
            .addStep(new BuildableStep("Choose a Crafting Table")
                    .addSubStep(new BuildableStep("Docks"))
                    .addImage()
                    .addSubStep(new BuildableStep("Cafeteria"))
                    .addSubStep(new BuildableStep("Behind Electric Cherry on the way up to the roof.")))
            .addStep(new BuildableStep("Find the Bars")
                    .addSubStep(new BuildableStep("In the spiral staircase room that goes down to the docks."))
                    .addSubStep(new BuildableStep("At the bottom of the spiral staircase, past the number input, to the left in the dead-end hallway leaning against a corner near the door."))
                    .addSubStep(new BuildableStep("Outside the generator room in the corner outside.")))
            .addStep(new BuildableStep("Find the Handle")
                    .addSubStep(new BuildableStep("In the generator room on a shelf."))
                    .addSubStep(new BuildableStep("In the generator room next to a generator on the floor."))
                    .addSubStep(new BuildableStep("In the generator room on a bottom shelf under a skull and candle.")))
            .addStep(new BuildableStep("Find the Hand Trolley")
                    .addSubStep(new BuildableStep("On the dock in a corner across from the ocean."))
                    .addSubStep(new BuildableStep("On the dock against a crate near the water."))
                    .addSubStep(new BuildableStep("In a corner near a crate on the dock."))
            );
    public static final Buildable PackAPunch = new Buildable("Pack A Punch - Icarus", "Access to Pack-a-Punch on the Golden Gate Bridge")
            .addStep(new BuildableStep("Reach the Roof (Crafting Site)")
                    .addSubStep(new BuildableStep("The plane is built on the roof of the prison. The build site and ramp are located there."))
                    .addSubStep(new BuildableStep("Access the roof by entering Afterlife, going through the portal in the walkway with many doors, jumping up, and shocking the voltmeter next to the roof door.")))
            .addStep(new BuildableStep("Retrieve the Uniforms")
                    .addSubStep(new BuildableStep("Go to the shower rooms below the cafeteria and open the gate to the laundry machine with the Warden's Key."))
                    .addSubStep(new BuildableStep("Enter Afterlife and shock the voltmeter opposite the machine."))
                    .addSubStep(new BuildableStep("Activate the laundry machine. This triggers a lockdown with fog and zombies (and potentially Brutus). Pick up the uniforms once finished.")))
            .addStep(new BuildableStep("Retrieve the Rigging")
                    .addSubStep(new BuildableStep("Go to the spiral staircase in the Citadel Tunnels and open the small gate to the electric number pad with the key."))
                    .addSubStep(new BuildableStep("Go into Afterlife at the top of the staircase. As you float down, find three numbers appearing on the walls."))
                    .addSubStep(new BuildableStep("Shock the number pad to match the code. Retrieve the rigging from the elevator in the lower room before the 60-second timer runs out.")))
            .addStep(new BuildableStep("Retrieve the Engine")
                    .addSubStep(new BuildableStep("Go to the docks and overload the three generators by shocking their associated panels in Afterlife (one panel is in a side room)."))
                    .addSubStep(new BuildableStep("Pick up the engine in the Warden's Office, which is now accessible behind the disabled electrified door.")))
            .addStep(new BuildableStep("Retrieve the Valves")
                    .addSubStep(new BuildableStep("Go to the infirmary next to the Cerberus head."))
                    .addSubStep(new BuildableStep("Open the locked glass case using the Warden's Key and pick up the valves.")))
            .addStep(new BuildableStep("Retrieve the Tank")
                    .addSubStep(new BuildableStep("Go to the docks next to the M1927 and open the gate with the key."))
                    .addSubStep(new BuildableStep("Solo: Shock the voltmeter in Afterlife to open the gate to the tank."))
                    .addSubStep(new BuildableStep("Co-op: Coordinate with a teammate; one shocks the panel to toggle gates while the other retrieves the tank part.")))
            .addStep(new BuildableStep("Construct and Board Icarus")
                    .addSubStep(new BuildableStep("Bring all five parts to the roof and construct the plane on the ramp."))
                    .addSubStep(new BuildableStep("All players must board the plane to fly to the Golden Gate Bridge for Pack-a-Punch access."))
            );
    public static final List<Buildable> MOTD_Buildables = Arrays.asList(
            FreeBlundergat,
            HellsRetriever,
            HellsRedeemer,
            AcidGatKit,
            ZombieShield,
            PackAPunch
    );
}
