package com.example.the_ultimate_easter_egg_guide.Storyline.CreaturesData;

public enum Enemy_Creatures
{
    Test,
    Zombie,
    Hellhound,
    Nova6Crawler,
    PentagonThief,
    GeorgeRomero,
    NapalmZombie,
    ShriekerZombie,
    ShangriLaMonkeys,
    AscensionMonkeys,
    MoonAstronaut,
    Denizens,
    Avagadro,
    Brutus,
    JumpingJacks,
    Witches,
    PanzerSoldat,
    TemplarZombies,
    Margwa,
    Paracite,
    Meatballs,
    Keepers,
    KeeperBoss,
    SkeletonZombie,
    TheShadowMan,
    Thrasher,
    Spiders,
    SpiderBoss,
    ThrasherBoss,
    RussianMangler,
    ValkyrieDrone,
    Dragon,
    NikoliMech,
    Furies,

    //BO4+
    Stoker,
    BleightFather,
    CatalystZombie,
    GiantEyeball, //Voyage Boss Fight
    Tigers,
    Destroyer,
    Merroter,
    Warewolf,
    NosForotues,
    WarewolfBoss,
    Spartwa,
    Gigganeese,
    Pegasis,
    Percious,
    Megaton,
    Mimic,
    Orda,

}
