package com.example.the_ultimate_easter_egg_guide.MapData.BOII.EasterEggs;

import com.example.the_ultimate_easter_egg_guide.Models.Maps.EasterEgg;
import com.example.the_ultimate_easter_egg_guide.Models.Maps.EasterEggStep;
import com.example.the_ultimate_easter_egg_guide.Models.Maps.Procedure;

import java.util.Arrays;
import java.util.List;

public class MOTD_EasterEggs {
    public static final EasterEgg PopGoesTheWeasel = new EasterEgg("Pop Goes the Weasel",
            "Pop Goes the Weasel achievement. Two outcomes: break the cycle or continue the cycle.")
            .addStep(new EasterEggStep("Prerequisite: Free Blundergat")
                    .addSubStep(new EasterEggStep("Obtain the Hell's Retriever first."))
                    .addSubStep(new EasterEggStep("Collect five blue skulls by throwing a charged Hell's Retriever at each one."))
                    .addSubStep(new EasterEggStep("The skulls are visible in Afterlife or through the Spectral Shield's spectral vision."))
                    .addSubStep(new EasterEggStep("When all five skulls are collected, the Demonic Announcer will laugh."))
                    .addSubStep(new EasterEggStep("The free Blundergat will appear on the Warden's table in the Warden's Office."))
                    .addSubStep(new EasterEggStep("Pick up the free Blundergat from the Warden's table."))
                    .addSubStep(new EasterEggStep("The Mystery Box Blundergat does not count for this Easter egg.")))
            .addStep(new EasterEggStep("Prerequisite: Spoon")
                    .addSubStep(new EasterEggStep("Complete the cycle at least once by going to the Golden Gate Bridge and returning through the electric chair."))
                    .addSubStep(new EasterEggStep("Find the jail cell with the blue and green movie poster \"Escape from the Tomb\" near the Warden's Office."))
                    .addSubStep(new EasterEggStep("Throw a frag grenade or the Hell's Retriever at the poster to remove it."))
                    .addSubStep(new EasterEggStep("A hole and Afterlife symbol will appear behind the poster."))
                    .addSubStep(new EasterEggStep("Enter Afterlife and go through the new Afterlife doorway on the wall opposite the Warden's Office, next to the high voltage panel."))
                    .addSubStep(new EasterEggStep("Zap the spoon on the ground next to the crack with the skull."))
                    .addSubStep(new EasterEggStep("The Demonic Announcer will laugh when done correctly.")))
            .addStep(new EasterEggStep("Get the Spoon from the Cafeteria")
                    .addSubStep(new EasterEggStep("Go to the Cafeteria and find the barrier at the back."))
                    .addSubStep(new EasterEggStep("The spoon is on the table against the left wall inside the barrier."))
                    .addSubStep(new EasterEggStep("Throw the Hell's Retriever at the spoon to get it."))
                    .addSubStep(new EasterEggStep("Brutus will speak when the spoon is collected."))
                    .addSubStep(new EasterEggStep("Each player who wants the Golden Spork must do this step.")))
            .addStep(new EasterEggStep("Step 1: Activate the Number Pad")
                    .addSubStep(new EasterEggStep("Complete the cycle at least three times."))
                    .addSubStep(new EasterEggStep("At least one player must have the free Blundergat and the spoon."))
                    .addSubStep(new EasterEggStep("Go to the spiral staircase between the Citadel Tunnels and the docks."))
                    .addSubStep(new EasterEggStep("The number pad will be rapidly changing and making constant clicking sounds.")))
            .addStep(new EasterEggStep("Enter the Prison Numbers")
                    .addSubStep(new EasterEggStep("Enter Afterlife and input the mobsters' prison numbers on the number pad."))
                    .addSubStep(new EasterEggStep("Enter 101."))
                    .addSubStep(new EasterEggStep("Enter 481."))
                    .addSubStep(new EasterEggStep("Enter 386."))
                    .addSubStep(new EasterEggStep("Enter 872."))
                    .addSubStep(new EasterEggStep("The numbers can be entered in any order."))
                    .addSubStep(new EasterEggStep("After each number, the pad will blink and shuffle."))
                    .addSubStep(new EasterEggStep("Tip: have a teammate partially revive you to extend Afterlife time, or enter two numbers, revive, re-enter Afterlife, and enter the other two.")))
            .addStep(new EasterEggStep("Listen to Stanley Ferguson")
                    .addSubStep(new EasterEggStep("When the numbers are entered correctly, Brutus will speak."))
                    .addSubStep(new EasterEggStep("The screen will turn black and white."))
                    .addSubStep(new EasterEggStep("Stanley Ferguson will begin narrating.")))
            .addStep(new EasterEggStep("Find the Headphones")
                    .addSubStep(new EasterEggStep("After the narration, pairs of headphones will appear in sequence like power-ups."))
                    .addSubStep(new EasterEggStep("Listen to each pair of headphones fully before the next one appears."))
                    .addSubStep(new EasterEggStep("The headphones do not despawn."))
                    .addSubStep(new EasterEggStep("The Demonic Announcer will laugh after each one.")))
            .addStep(new EasterEggStep("Headphone 1")
                    .addSubStep(new EasterEggStep("Find the first pair of headphones on the staircase back up to the Citadel Tunnels.")))
            .addStep(new EasterEggStep("Headphone 2")
                    .addSubStep(new EasterEggStep("Find the second pair of headphones near Double Tap Root Beer.")))
            .addStep(new EasterEggStep("Headphone 3")
                    .addSubStep(new EasterEggStep("Find the third pair of headphones on the walkway between the Warden's Office and the Cafeteria.")))
            .addStep(new EasterEggStep("Headphone 4")
                    .addSubStep(new EasterEggStep("Find the fourth pair of headphones on the staircase from the Cafeteria to the infirmary.")))
            .addStep(new EasterEggStep("Headphone 5")
                    .addSubStep(new EasterEggStep("Find the fifth pair of headphones on the staircase to the roof.")))
            .addStep(new EasterEggStep("Step 2: Board the Plane in Afterlife")
                    .addSubStep(new EasterEggStep("Enter Afterlife and go to the plane."))
                    .addSubStep(new EasterEggStep("Use the action button next to the plane to board it."))
                    .addSubStep(new EasterEggStep("The plane does not need to be refueled."))
                    .addSubStep(new EasterEggStep("There is no prompt, so simply use the action button next to the plane.")))
            .addStep(new EasterEggStep("Crash Into the Bridge")
                    .addSubStep(new EasterEggStep("All players will be placed on the plane."))
                    .addSubStep(new EasterEggStep("The plane will take off and crash into the Golden Gate Bridge."))
                    .addSubStep(new EasterEggStep("Everyone lands in Afterlife with their bodies in the electric chairs."))
                    .addSubStep(new EasterEggStep("Each player must revive themselves.")))
            .addStep(new EasterEggStep("Weasel Becomes the Enemy")
                    .addSubStep(new EasterEggStep("After everyone revives themselves, Weasel will appear as an enemy."))
                    .addSubStep(new EasterEggStep("The other mobsters can damage Weasel."))
                    .addSubStep(new EasterEggStep("Weasel can damage the other mobsters."))
                    .addSubStep(new EasterEggStep("Zombies do not attack Weasel."))
                    .addSubStep(new EasterEggStep("The Pop Goes the Weasel achievement unlocks here.")))
            .addStep(new EasterEggStep("Break the Cycle")
                    .addSubStep(new EasterEggStep("To break the cycle, Weasel must kill all the other mobsters."))
                    .addSubStep(new EasterEggStep("Weasel has higher damage resistance than the other players."))
                    .addSubStep(new EasterEggStep("When the other mobsters are dead, either by Weasel or zombies, the game ends."))
                    .addSubStep(new EasterEggStep("The camera pans out from the Golden Gate Bridge with an orchestral version of the ending song."))
                    .addSubStep(new EasterEggStep("This is the canon ending.")))
            .addStep(new EasterEggStep("Continue the Cycle")
                    .addSubStep(new EasterEggStep("To continue the cycle, the other mobsters must kill Weasel."))
                    .addSubStep(new EasterEggStep("When Weasel is dead, the game ends with the regular camera angle and a unique song."))
    );
    public static final EasterEgg RustyCage = new EasterEgg("Rusty Cage")
            .addStep(new EasterEggStep("Find the First Bottle")
                    .addSubStep(new EasterEggStep("Find the first bottle on a bookshelf in the library near the spawn area.")))
            .addStep(new EasterEggStep("Find the Second Bottle")
                    .addSubStep(new EasterEggStep("Find the second bottle in the infirmary, near one of the baths filled with blood.")))
            .addStep(new EasterEggStep("Find the Third Bottle")
                    .addSubStep(new EasterEggStep("Find the third bottle on the docks, tucked between a crate and a fence.")))
            .addStep(new EasterEggStep("Play the Song")
                    .addSubStep(new EasterEggStep("Activate all three bottles to play \"Rusty Cage.\""))
    );
    public static final EasterEgg WhereAreWeGoing = new EasterEgg("Where Are We Going")
            .addStep(new EasterEggStep("Find the Warden's Key")
                    .addSubStep(new EasterEggStep("Find and pick up the Warden's Key.")))
            .addStep(new EasterEggStep("Go to the Power Switch")
                    .addSubStep(new EasterEggStep("Go to the power switch area near the underground elevator.")))
            .addStep(new EasterEggStep("Enter 935")
                    .addSubStep(new EasterEggStep("Use the numbers puzzle next to the elevator."))
                    .addSubStep(new EasterEggStep("Input 935 into the number counter.")))
            .addStep(new EasterEggStep("Play the Song")
                    .addSubStep(new EasterEggStep("The song \"Where Are We Going\" will begin playing."))
    );
    public static final EasterEgg SecretEnding = new EasterEgg("Secret Ending")
            .addStep(new EasterEggStep("Start the Match")
                    .addSubStep(new EasterEggStep("At the beginning of the match, do not move.")))
            .addStep(new EasterEggStep("Wait in Afterlife")
                    .addSubStep(new EasterEggStep("Wait for the Afterlife timer to be fully consumed.")))
            .addStep(new EasterEggStep("Trigger the Secret Ending")
                    .addSubStep(new EasterEggStep("The screen will turn black and white."))
                    .addSubStep(new EasterEggStep("The mobsters will bleed out."))
                    .addSubStep(new EasterEggStep("Samantha's lullaby will play as the view rises from the spawn room to the sky."))
    );
    public static final EasterEgg JumpScare = new EasterEgg("Jump Scare")
            .addStep(new EasterEggStep("Get a Sniper Rifle")
                    .addSubStep(new EasterEggStep("Obtain a sniper rifle, such as the Barrett M82A1 or DSR 50.")))
            .addStep(new EasterEggStep("Go to the Roof")
                    .addSubStep(new EasterEggStep("Go to the roof where the plane is assembled."))
                    .addSubStep(new EasterEggStep("Head to the far end of the roof, to the left of the runway.")))
            .addStep(new EasterEggStep("Scope in on the Fireworks")
                    .addSubStep(new EasterEggStep("Look toward the firework display in the distance."))
                    .addSubStep(new EasterEggStep("Scope in on the fireworks with the sniper rifle.")))
            .addStep(new EasterEggStep("Trigger the Jump Scare")
                    .addSubStep(new EasterEggStep("A distorted face will flash on screen for a split second."))
                    .addSubStep(new EasterEggStep("A high-pitched scream will play when the jump scare triggers."))
    );
    public static final EasterEgg AudioLogs = new EasterEgg("Audio Logs")
            .addStep(new EasterEggStep("Find the Number Counter")
                    .addSubStep(new EasterEggStep("Find the number counter that operates the underground elevator.")))
            .addStep(new EasterEggStep("Enter the Prison Numbers")
                    .addSubStep(new EasterEggStep("Enter the mobsters' prison numbers into the counter."))
                    .addSubStep(new EasterEggStep("Enter 101."))
                    .addSubStep(new EasterEggStep("Enter 481."))
                    .addSubStep(new EasterEggStep("Enter 386."))
                    .addSubStep(new EasterEggStep("Enter 872.")))
            .addStep(new EasterEggStep("Listen to the Audio Logs")
                    .addSubStep(new EasterEggStep("Each number gives access to an audio log."))
                    .addSubStep(new EasterEggStep("Stanley Ferguson narrates the events at Alcatraz and explains the group's situation."))
    );
    public static final EasterEgg GoldenSpork = new EasterEgg("Golden Spork")
            .addStep(new EasterEggStep("Prerequisite")
                    .addSubStep(new EasterEggStep("Obtain the Hell's Retriever first. Reference the Hell's Retriever guide before starting this Easter egg."))
                    .addSubStep(new EasterEggStep("Obtain the Acid Gat or Vitriolic Withering before the zombie kill step.")))
            .addStep(new EasterEggStep("Reveal the Hidden Spoon")
                    .addSubStep(new EasterEggStep("Find the jail cell with the blue and green \"Escape from the Tomb\" poster near the Warden's Office."))
                    .addSubStep(new EasterEggStep("Throw the Hell's Retriever at the poster to remove it."))
                    .addSubStep(new EasterEggStep("Enter Afterlife and go through the new portal behind the poster."))
                    .addSubStep(new EasterEggStep("Zap the spoon on the floor to the right of the crack with the skull."))
                    .addSubStep(new EasterEggStep("The Demonic Announcer will laugh when done correctly.")))
            .addStep(new EasterEggStep("Obtain the Silver Spoon")
                    .addSubStep(new EasterEggStep("Go to the Cafeteria and find the barrier at the back."))
                    .addSubStep(new EasterEggStep("The spoon is on the table against the left wall inside the barrier."))
                    .addSubStep(new EasterEggStep("Throw the Hell's Retriever at the spoon to obtain the Silver Spoon."))
                    .addSubStep(new EasterEggStep("Brutus will speak when this is done correctly."))
                    .addSubStep(new EasterEggStep("Each player who wants the Golden Spork must do this individually.")))
            .addStep(new EasterEggStep("Place the Silver Spoon in the Bathtub")
                    .addSubStep(new EasterEggStep("Enter the infirmary and find the lone bathtub filled with blood."))
                    .addSubStep(new EasterEggStep("The bathtub is opposite a Mystery Box spawn."))
                    .addSubStep(new EasterEggStep("Hold the action button next to the bathtub."))
                    .addSubStep(new EasterEggStep("The Silver Spoon will appear and stir the blood."))
                    .addSubStep(new EasterEggStep("Each player must do this individually.")))
            .addStep(new EasterEggStep("Get Kills with the Acid Gat")
                    .addSubStep(new EasterEggStep("Go to the underground showers."))
                    .addSubStep(new EasterEggStep("Kill zombies with the Acid Gat or Vitriolic Withering."))
                    .addSubStep(new EasterEggStep("After about 50-70 kills, the Demonic Announcer will laugh again.")))
            .addStep(new EasterEggStep("Claim the Golden Spork")
                    .addSubStep(new EasterEggStep("Return to the infirmary and go back to the lone blood-filled bathtub."))
                    .addSubStep(new EasterEggStep("Hold the action button next to the bathtub."))
                    .addSubStep(new EasterEggStep("A zombified hand will rise from the blood holding the Golden Spork."))
                    .addSubStep(new EasterEggStep("Press the action button to take the Golden Spork."))
                    .addSubStep(new EasterEggStep("Each player who wants the Golden Spork must complete this step.")))
            .addStep(new EasterEggStep("If You Bleed Out")
                    .addSubStep(new EasterEggStep("If you bleed out and respawn after getting the Golden Spork, redo the bathtub and Acid Gat kill steps."))
                    .addSubStep(new EasterEggStep("The hand will rise again and you can retake the Golden Spork."))
    );
    public static final EasterEgg Brutus115 = new EasterEgg("Brutus 115")
            .addStep(new EasterEggStep("Find the Number Counter")
                    .addSubStep(new EasterEggStep("Go to the number counter on Mob of the Dead.")))
            .addStep(new EasterEggStep("Enter 115")
                    .addSubStep(new EasterEggStep("Enter 115 into the number counter.")))
            .addStep(new EasterEggStep("Listen for Brutus")
                    .addSubStep(new EasterEggStep("Brutus will whisper \"Not this time!\" or \"Maybe next time.\""))
                    .addSubStep(new EasterEggStep("The number will change to 666, then return to normal.")))
            .addStep(new EasterEggStep("Effect")
                    .addSubStep(new EasterEggStep("No other effects occur. This is a minor audio/visual Easter egg."))
    );
    public static final EasterEgg FreeBlundergat = new EasterEgg("Free Blundergat")
            .addStep(new EasterEggStep("Prerequisite")
                    .addSubStep(new EasterEggStep("Obtain the Hell's Retriever first. Reference the Hell's Retriever guide before starting this Easter egg."))
                    .addSubStep(new EasterEggStep("The Blundergat from the Mystery Box does not count for the main quest or this guide.")))
            .addStep(new EasterEggStep("Collect the Hidden Blue Skulls")
                    .addSubStep(new EasterEggStep("Use the Hell's Retriever to collect five hidden blue skulls around the map."))
                    .addSubStep(new EasterEggStep("Hold the tactical button to charge the Hell's Retriever before throwing it at each skull."))
                    .addSubStep(new EasterEggStep("The skulls are only visible in Afterlife or through the Spectral Shield's spectral vision."))
                    .addSubStep(new EasterEggStep("The skull locations are the same every game."))
                    .addSubStep(new EasterEggStep("When the charged Hell's Retriever hits a skull, it will return to you with the skull attached.")))
            .addStep(new EasterEggStep("Skull 1")
                    .addSubStep(new EasterEggStep("In the cell block just outside the library in the spawn area."))
                    .addSubStep(new EasterEggStep("The skull is inside a cell with a toilet.")))
            .addStep(new EasterEggStep("Skull 2")
                    .addSubStep(new EasterEggStep("On the roof, back left when coming onto the roof."))
                    .addSubStep(new EasterEggStep("The skull is sitting on an unreachable corner of the roof.")))
            .addStep(new EasterEggStep("Skull 3")
                    .addSubStep(new EasterEggStep("On the docks, across the water on another dock."))
                    .addSubStep(new EasterEggStep("Look near the third pillar from the left, close to the possible Mystery Box spawn.")))
            .addStep(new EasterEggStep("Skull 4")
                    .addSubStep(new EasterEggStep("Above Juggernog near the docks."))
                    .addSubStep(new EasterEggStep("Look up at the lamppost on the hill."))
                    .addSubStep(new EasterEggStep("You have to jump when throwing the Hell's Retriever, or collect it from the gondola as it moves.")))
            .addStep(new EasterEggStep("Skull 5")
                    .addSubStep(new EasterEggStep("In the Warden's Office, outside the window on a telephone pole."))
                    .addSubStep(new EasterEggStep("Look out the window to line up the throw."))
                    .addSubStep(new EasterEggStep("Do not board up the window because the planks can block the throw.")))
            .addStep(new EasterEggStep("Claim the Free Blundergat")
                    .addSubStep(new EasterEggStep("After all five skulls are collected, the Demonic Announcer will laugh."))
                    .addSubStep(new EasterEggStep("The Blundergat will appear on the Warden's table in the Warden's Office."))
                    .addSubStep(new EasterEggStep("Pick up the free Blundergat from the Warden's table."))
    );
    public static final EasterEgg HellsRetriever = new EasterEgg("Hell's Retriever")
            .addStep(new EasterEggStep("Feed the dog Heads")
                    .addSubStep(new EasterEggStep("Feed six zombies to each of the three dog heads around the map."))
                    .addSubStep(new EasterEggStep("Each head must be fed six zombies. When a head is complete, it will recede into the wall and the Dog icon on the wall will glow.")))
            .addStep(new EasterEggStep("Dog Head 1")
                    .addSubStep(new EasterEggStep("In the Broadway cell block, located near the B23R.")))
            .addStep(new EasterEggStep("Dog Head 2")
                    .addSubStep(new EasterEggStep("In the infirmary, adjacent to the Afterlife power box.")))
            .addStep(new EasterEggStep("Dog Head 3")
                    .addSubStep(new EasterEggStep("Near the workbench on the lower level of the docks.")))
            .addStep(new EasterEggStep("Claim the Hell's Retriever")
                    .addSubStep(new EasterEggStep("Once all three heads have receded and the Dog head icons are glowing, an area opens in the Citadel Tunnels beneath the sign of the three dog heads."))
                    .addSubStep(new EasterEggStep("Go down there and pick up the Hell's Retriever."))
    );
    public static final EasterEgg HellsRedeemer = new EasterEgg("Hell's Redeemer")
            .addStep(new EasterEggStep("Prerequisite")
                    .addSubStep(new EasterEggStep("Obtain the Hell's Retriever first. Reference the Hell's Retriever guide before starting this Easter egg.")))
            .addStep(new EasterEggStep("Kill Zombies with the Hell's Retriever")
                    .addSubStep(new EasterEggStep("Kill approximately 10-15 zombies with the Hell's Retriever."))
                    .addSubStep(new EasterEggStep("When done correctly, you will hear the sound of entering Afterlife and some music.")))
            .addStep(new EasterEggStep("Complete a Bridge Round")
                    .addSubStep(new EasterEggStep("Go to the Golden Gate Bridge on round 10 or higher."))
                    .addSubStep(new EasterEggStep("Spend at least one full round on the bridge using only the Hell's Retriever."))
                    .addSubStep(new EasterEggStep("Kill at least 30 zombies with the Hell's Retriever during that round."))
                    .addSubStep(new EasterEggStep("When the round ends, you should hear the Afterlife sound."))
                    .addSubStep(new EasterEggStep("Do not shoot any weapons during this round or the step will reset. Knifing the air is allowed.")))
            .addStep(new EasterEggStep("Throw the Hell's Retriever into Lava")
                    .addSubStep(new EasterEggStep("Throw the Hell's Retriever into the lava pit underneath the Cerberus head near the B23R."))
                    .addSubStep(new EasterEggStep("If done correctly, the Hell's Retriever will not return and you will hear the Afterlife sound again."))
                    .addSubStep(new EasterEggStep("The lava is under the ramp that leads to the B23R and Cerberus head. Throw the retriever into the lava from there.")))
            .addStep(new EasterEggStep("Pick Up the Hell's Redeemer")
                    .addSubStep(new EasterEggStep("On any following round, go to the Citadel Tunnels where you originally obtained the Hell's Retriever."))
                    .addSubStep(new EasterEggStep("The retriever should be gone and the aura should be blue instead of red."))
                    .addSubStep(new EasterEggStep("Enter Afterlife and pick up the Hell's Redeemer."))
    );
    public static final EasterEgg AcidGatKit = new EasterEgg("Acid Gat Kit")
            .addStep(new EasterEggStep("Choose a Crafting Table")
                    .addSubStep(new EasterEggStep("Docks"))
                    .addSubStep(new EasterEggStep("Cafeteria"))
                    .addSubStep(new EasterEggStep("Behind Electric Cherry on the way up to the roof.")))
            .addStep(new EasterEggStep("Find the Motor")
                    .addSubStep(new EasterEggStep("Right as you enter the Warden's quarters, to the right of the wall buy on the floor."))
                    .addSubStep(new EasterEggStep("To the left of the Mystery Box spawn on the floor in the Warden's Office."))
                    .addSubStep(new EasterEggStep("To the left of the fireplace, to the left of Speed Cola in the Warden's Office.")))
            .addStep(new EasterEggStep("Find the Case")
                    .addSubStep(new EasterEggStep("Near the library through the C-D gate, sitting on a table near the jail cell."))
                    .addSubStep(new EasterEggStep("Under the staircase in the hallway leading to the Warden's Office, also known as Michigan Avenue."))
                    .addSubStep(new EasterEggStep("Near the top of the stairs from the laundromat, across from the Afterlife switch, on the floor.")))
            .addStep(new EasterEggStep("Find the Acid Bottle")
                    .addSubStep(new EasterEggStep("On the way up to the roof, in the left corridor opposite the bloody bathtubs, on a table."))
                    .addSubStep(new EasterEggStep("In the second room with the bloody bathtubs on the way up to the roof."))
                    .addSubStep(new EasterEggStep("In the first room with the bloody bathtubs."))
    );
    public static final EasterEgg ZombieShield = new EasterEgg("Zombie Shield", "A back-mounted shield that protects from rear attacks and can be used as a melee weapon.")
            .addStep(new EasterEggStep("Choose a Crafting Table")
                    .addSubStep(new EasterEggStep("Docks"))
                    .addImage()
                    .addSubStep(new EasterEggStep("Cafeteria"))
                    .addSubStep(new EasterEggStep("Behind Electric Cherry on the way up to the roof.")))
            .addStep(new EasterEggStep("Find the Bars")
                    .addSubStep(new EasterEggStep("In the spiral staircase room that goes down to the docks."))
                    .addSubStep(new EasterEggStep("At the bottom of the spiral staircase, past the number input, to the left in the dead-end hallway leaning against a corner near the door."))
                    .addSubStep(new EasterEggStep("Outside the generator room in the corner outside.")))
            .addStep(new EasterEggStep("Find the Handle")
                    .addSubStep(new EasterEggStep("In the generator room on a shelf."))
                    .addSubStep(new EasterEggStep("In the generator room next to a generator on the floor."))
                    .addSubStep(new EasterEggStep("In the generator room on a bottom shelf under a skull and candle.")))
            .addStep(new EasterEggStep("Find the Hand Trolley")
                    .addSubStep(new EasterEggStep("On the dock in a corner across from the ocean."))
                    .addSubStep(new EasterEggStep("On the dock against a crate near the water."))
                    .addSubStep(new EasterEggStep("In a corner near a crate on the dock."))
    );
    public static final EasterEgg PackAPunch = new EasterEgg("Pack A Punch - Icarus", "Access to Pack-a-Punch on the Golden Gate Bridge")
            .addStep(new EasterEggStep("Reach the Roof (Crafting Site)")
                    .addSubStep(new EasterEggStep("The plane is built on the roof of the prison. The build site and ramp are located there."))
                    .addSubStep(new EasterEggStep("Access the roof by entering Afterlife, going through the portal in the walkway with many doors, jumping up, and shocking the voltmeter next to the roof door.")))
            .addStep(new EasterEggStep("Retrieve the Uniforms")
                    .addSubStep(new EasterEggStep("Go to the shower rooms below the cafeteria and open the gate to the laundry machine with the Warden's Key."))
                    .addSubStep(new EasterEggStep("Enter Afterlife and shock the voltmeter opposite the machine."))
                    .addSubStep(new EasterEggStep("Activate the laundry machine. This triggers a lockdown with fog and zombies (and potentially Brutus). Pick up the uniforms once finished.")))
            .addStep(new EasterEggStep("Retrieve the Rigging")
                    .addSubStep(new EasterEggStep("Go to the spiral staircase in the Citadel Tunnels and open the small gate to the electric number pad with the key."))
                    .addSubStep(new EasterEggStep("Go into Afterlife at the top of the staircase. As you float down, find three numbers appearing on the walls."))
                    .addSubStep(new EasterEggStep("Shock the number pad to match the code. Retrieve the rigging from the elevator in the lower room before the 60-second timer runs out.")))
            .addStep(new EasterEggStep("Retrieve the Engine")
                    .addSubStep(new EasterEggStep("Go to the docks and overload the three generators by shocking their associated panels in Afterlife (one panel is in a side room)."))
                    .addSubStep(new EasterEggStep("Pick up the engine in the Warden's Office, which is now accessible behind the disabled electrified door.")))
            .addStep(new EasterEggStep("Retrieve the Valves")
                    .addSubStep(new EasterEggStep("Go to the infirmary next to the Cerberus head."))
                    .addSubStep(new EasterEggStep("Open the locked glass case using the Warden's Key and pick up the valves.")))
            .addStep(new EasterEggStep("Retrieve the Tank")
                    .addSubStep(new EasterEggStep("Go to the docks next to the M1927 and open the gate with the key."))
                    .addSubStep(new EasterEggStep("Solo: Shock the voltmeter in Afterlife to open the gate to the tank."))
                    .addSubStep(new EasterEggStep("Co-op: Coordinate with a teammate; one shocks the panel to toggle gates while the other retrieves the tank part.")))
            .addStep(new EasterEggStep("Construct and Board Icarus")
                    .addSubStep(new EasterEggStep("Bring all five parts to the roof and construct the plane on the ramp."))
                    .addSubStep(new EasterEggStep("All players must board the plane to fly to the Golden Gate Bridge for Pack-a-Punch access."))
    );


    public static final List<EasterEgg> MOTD_MainQuests = Arrays.asList(
        PopGoesTheWeasel
    );
    public static final List<EasterEgg> MOTD_SideQuests = Arrays.asList(
        RustyCage,
        WhereAreWeGoing,
        SecretEnding,
        JumpScare,
        AudioLogs,
        GoldenSpork,
        Brutus115
    );
    public static final List<Procedure> MOTD_Buildables = Arrays.asList(
        FreeBlundergat,
        HellsRetriever,
        HellsRedeemer,
        AcidGatKit,
        ZombieShield,
        PackAPunch
    );
}
